services:
  - type: web
    name: posture-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**/*
    rootDir: backend
